### ISSUE TITLE
SSL Certificate Error in Production Mode with DocuSign API

### ISSUE THREAD

**Issue by Mrad-Hamza** [docusign/docusign-esign-php-client#232]
Hello, 
I'm encountering an issue with the DocuSign API. While everything works perfectly in test mode, switching to production mode triggers the following error:

> DocuSign\eSign\Client\ApiException: API call to https://account.docusign.com/oauth/token failed: SSL certificate problem: self signed certificate in certificate chain in App\ElectronicSign\vendor\docusign\esign-client\src\Client\ApiClient.php:321 Stack trace: #0 App\ElectronicSign\vendor\docusign\esign-client\src\Client\ApiClient.php(597): DocuSign\eSign\Client\ApiClient->callApi('/oauth/token', 'POST', Array, 'assertion=eyJ0e...', Array, NULL, NULL, true) #1 App\ElectronicSign\Service\SignatureStrategy\Docusign\DocusignSignature.php(181): DocuSign\eSign\Client\ApiClient->requestJWTUserToken('0eb63ea9-e4a5-4...', '1dbd6254-b17d-4...', '-----BEGIN RSA ...', Array) #2 App\ElectronicSign\Service\SignatureStrategy\Docusign\DocusignSignature.php(278): App\ElectronicSign\Service\SignatureStrategy\Docusign\DocusignSignature->createJWTUserToken()

Details:

 - The integration key is valid for production mode.
 - The SSL certificate being used is not self-signed and is trusted by Microsoft (listed here: [Microsoft Trusted Root Program](https://ccadb.my.salesforce-sites.com/microsoft/IncludedCACertificateReportForMSFT)).
Could you provide insights on what might be causing this error?

Thank you for your assistance.

**Comment by prudhvik-docusign** [comment]
Hi @Mrad-Hamza , is this issue resolved?
